"""How many provisions each indicator may spend an LLM call on, per economy.

One constant for every economy is provably wrong. Measured against the panel's own Round-1
Database on the built corpora (`logs/sweep_final.json`, `logs/validate_k450.json`):

    shortlist k   SG      AU      MY      provision-recall
    40            1.00    0.60    1.00
    150           1.00    0.80    1.00
    300           1.00    1.00    1.00

Singapore's cited provisions all arrive by rank 40 (`median_rank_of_target = 1`); Australia's
need 300. The shipped formula — `clamp(ceil(n x 5%), 40, 450)` — gave a 4,840-provision
Singapore P6 crawl 242 candidates per indicator, 968 LLM calls, to fetch things sitting in the
top forty. Australia at the same setting is not over-spending at all.

So the budget is a per-economy TABLE, and the table is generated by measurement, never by
hand: `tools/measure_budget.py` runs the shipped selector over the built corpus at a ladder of
k values and writes `data/retrieval_budget.json` with the recall it observed and the date it
observed it. This module only reads that file.

An economy with no measured entry keeps the conservative default (the current formula, cap
`retrieve_max_top_k`). That is the honest direction to be wrong in: unmeasured retrieval is
unknown retrieval, and the cost of grading too much is money, while the cost of grading too
little is a missing row in the submission. Timor-Leste, which the panel scores in no database
we hold, can therefore never be silently narrowed.
"""
from __future__ import annotations

import json
import math
from typing import Any

from ..config import ROOT, settings

BUDGET_JSON = ROOT / "data" / "retrieval_budget.json"

_cache: dict[str, Any] | None = None


def _load() -> dict[str, Any]:
    global _cache
    if _cache is None:
        try:
            _cache = json.loads(BUDGET_JSON.read_text(encoding="utf-8"))
        except Exception:       # noqa: BLE001 — a missing/corrupt table means "unmeasured"
            _cache = {"economies": {}}
    return _cache


def reload() -> None:
    """Drop the cached table (tests, and after tools/measure_budget.py rewrites it)."""
    global _cache
    _cache = None


def entry(economy: str | None) -> dict[str, Any] | None:
    """The measured entry for an economy, or None when it has never been measured."""
    if not economy:
        return None
    return _load().get("economies", {}).get(str(economy).upper())


def shortlist_size(economy: str | None, n_provisions: int, top_k: int = 5) -> tuple[int, str]:
    """(candidates per indicator, one-line reason).

    The reason is returned rather than logged here so the caller can put it in the run log
    verbatim — a budget that shrinks a run by 6x has to say why on the record.
    """
    default_k = min(n_provisions, settings.retrieve_max_top_k,
                    max(top_k, settings.retrieve_top_k,
                        math.ceil(n_provisions * settings.retrieve_fraction)))
    if not settings.retrieval_budget_enabled:
        return default_k, f"top_k={default_k} (per-economy budget disabled)"

    e = entry(economy)
    if not e:
        return default_k, (f"top_k={default_k} (no measured budget for "
                           f"{economy or 'this economy'} — conservative default)")

    cap = int(e.get("cap") or settings.retrieve_max_top_k)
    floor = int(e.get("floor") or settings.retrieve_top_k)
    # REVERTED 2026-08-31, same day, on the evidence of the run it produced. For one afternoon
    # this read `min(n, max(cap, floor, top_k))` — "a measured cap IS the depth" — on the
    # argument that writing it as `min(n, cap, max(floor, 5% of n))` let the heuristic override
    # the measurement and never test it. The retrieval measurement was right and the conclusion
    # was wrong, because retrieval recall is a CEILING, not an outcome. Measured end to end
    # across six economies:
    #
    #     depth ~250 -> 450     cost $2.07 -> $7.39, 72 -> 186 minutes
    #                           cited provisions found  55 -> 72   (+17)
    #                           rows exported        1,149 -> 2,121
    #                           precision on new rows   57% -> 57%  (independent audit,
    #                                                    control group, MN excluded)
    #                           => false rows          ~494 -> ~912  (+418)
    #
    # Seventeen more correct answers bought at twenty-five wrong rows each. Criterion C2b
    # scores citation fidelity, so those rows cost marks, not just money. The extra depth
    # cannot pay until the acceptance side can refuse: 21% of what retrieval already sends
    # (36-41% on pillar 6) contains no concept term of the pillar at all, the grader emits
    # legal_match=0.9 on 79% of what it accepts, and the confidence formula has never rejected
    # a single row (floor ~0.71 against a 0.60 threshold).
    #
    # So the cap is a CEILING again. It stays measured, and it stays in the table with the
    # recall it was measured at — raise it when the grader and the confidence score can tell a
    # good candidate from a nearby one, not before.
    k = min(n_provisions, cap, max(top_k, floor,
                                   math.ceil(n_provisions * settings.retrieve_fraction)))
    recall = e.get("prov_recall")
    saved = default_k - k
    why = (f"top_k={k} (measured for {economy}: in-corpus prov-recall "
           f"{recall if recall is not None else '?'} at k={e.get('measured_k', cap)} "
           f"on {e.get('measured_on', 'an unrecorded date')})")
    if saved > 0:
        why += f" — {saved} fewer candidates/indicator than the untuned default"
    elif saved < 0:
        why += f" — {-saved} MORE candidates/indicator than the untuned default would give"
    return k, why
